apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-demo
  labels:
    app: webapp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-demo
        tier: webapp-demo
    spec:
      containers:
      - image: $REPOSITORY
        name: webapp-demo
        ports:
        - containerPort: 8080
          name: webapp-demo
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-demo
  labels:
    app: webapp-demo
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webapp-demo
    tier: webapp-demo
  type: LoadBalancer
